### ISSUE TITLE
Add our COC/Anti-harassment policy

### ISSUE THREAD

**Issue by latazzajones** [charmCityJs/charmcityjs.github.io#2]
This should be in a prominent place. Here's a link http://www.meetup.com/charmcityjs/pages/charmCityJS_Anti-Harassment_Policy/

This should be both linked so that people can see where it lives on the meetup page but it would also be great to have the text on a tab or collapsed accordion thingy.  

_BIG SUPER BONUS POINTS_
Updated dynamically using the meetup api (not sure if that's even possible).

**Comment by jasonrhodes** [comment]
The link is already added, but if you can take a stab at the other stuff here, that'd be great too... :)

**Comment by latazzajones** [comment]
:heart: @jasonrhodes for the win!

**Comment by ecarlisle** [comment]
I checked the Meetup API and don't think we could directly import to the site from meetup or export to Meetup from the site.  I'm happy to add the license agreement.  In doing so and adding more context, I'm wondering if this and the other nav options should be placed on a top navigation bar.  I dig the simplicity of the site so it wouldn't have to be all Vegas, but would allow for more organized content growth.

**Comment by jasonrhodes** [comment]
@ecarlisle thanks!!! Sorry it took me a while to get back to you. This is great, I have only 2 small requests:
- Moving the buttons up was a good call. Can you make them hoverable for their whole space instead of just the text, like they currently are?
- Seems like the CoC title/head should align with the text below, either by un-indenting the text or indenting the headline, whatever you think works better.

Other than that, looks great.

**Comment by ecarlisle** [comment]
Great, thanks for the feedback @jasonrhodes !
I've committed those changes to the branch.
I hope you don't mind the scope creep, but I added an /assets folder and moved non-HTML static assets there. Force of habit but I can revert if that's a "rather not." 

Thanks!
